### ISSUE TITLE
2 more typos

### ISSUE THREAD

**Issue by Colins2** [rutura/Qt6QMLBeginnersCode#3]
Page 121 - a very minor typo. You write Now the fund begins.... should be now the fun....
Pages 127+ You have changed the name of the "Sender" object to "Notifier" which doesn't work.

FYI, I am not using any downloaded code, I am typing everything direct from the book text

**Comment by rutura** [comment]
Thanks for these reports @Colins2 . Please remember that the suggestions are collected at this git repo : https://github.com/rutura/Qt6QMLBeginnersBookRelease .

I will get around and fix all these. Keep them coming.

Daniel.
